ALTER TABLE fwi_state
    ALTER COLUMN ffmc TYPE DOUBLE PRECISION,
    ALTER COLUMN dmc TYPE DOUBLE PRECISION,
    ALTER COLUMN dc TYPE DOUBLE PRECISION,
    ALTER COLUMN isi TYPE DOUBLE PRECISION,
    ALTER COLUMN bui TYPE DOUBLE PRECISION,
    ALTER COLUMN fwi TYPE DOUBLE PRECISION;
