[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
geojson.workspace = true
grid = { path = "../grid" }
risk = { path = "../risk" }
serde.workspace = true
serde_json.workspace = true
store = { path = "../store" }
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true

[dev-dependencies]
dotenvy.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower.workspace = true

[lints]
workspace = true
